### PR TITLE
use mp4 instead of gif

### PR DESCRIPTION
**Pull request by liorocks**
Total gif size is about 130MB.

If you replace it with mp4, it will be about 15MB. 

P.S. Would love to see your version of this GIF 😁  
https://i.giphy.com/media/1jnyRP4DorCh2/giphy.gif

### CODE REVIEW

**Comment by kentcdodds** [comment]
Nice! One thing I like about the app is how easy it is to download the gif is I want to use it in Twitter or something. Could we get a button for downloading the gif?

**Comment by kentcdodds** [comment]
This was actually inspired by that gif

IZ2eI0akSxm0R0k50g

**Comment by liorocks** [comment]
> Could we get a button for downloading the gif?

My initial thought was to add `a` tag with `download` attribute, but it will not download automatically, because of the cross-domain issues.

**Comment by liorocks** [comment]
@kentcdodds So, how about icon with an external link to GIF instead? 

image

Or button, that copies the direct link to GIF.

image

**Comment by kentcdodds** [comment]
I just realized how bad this is for people on mobile with a limited data plan. So I'm merging your PR now and I'd welcome an additional PR to make it easy to download the gif. What about a download icon. Something like:

image

**Comment by kentcdodds** [comment]
> but it will not download automatically, because of the cross-domain issues.

Just noticed this. That's a bummer. In that case, I think a copy-to-clipboard would be nice and then maybe clicking on the image would just open giphy...

**Pull request merged**
